name: My First Workflow

on: push

jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  
      - name: Welcome Message
        run: echo "Hello There !!!"

      - name: List Files
        run: ls

      - name: Read README
        run: cat README.md
